# Generated by Django 4.2.6 on 2023-10-19 13:08

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tg_id', models.BigIntegerField(blank=True, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('is_ordered', models.BooleanField(default=False)),
                ('security_code', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
